# coding: utf-8

"""
    Cortex XSOAR API

    This is the public REST API to integrate with the Cortex XSOAR server. HTTP request can be sent using any HTTP-client.  For an example dedicated client take a look at: https://github.com/demisto/demisto-py.  Requests must include API-key that can be generated in the Cortex XSOAR web client under 'Settings' -> 'Integrations' -> 'API keys'   Optimistic Locking and Versioning\\:  When using Cortex XSOAR REST API, you will need to make sure to work on the latest version of the item (incident, entry, etc.), otherwise, you will get a DB version error (which not allow you to override a newer item). In addition, you can pass 'version\\: -1' to force data override (make sure that other users data might be lost).  Assume that Alice and Bob both read the same data from Cortex XSOAR server, then they both changed the data, and then both tried to write the new versions back to the server. Whose changes should be saved? Alice’s? Bob’s? To solve this, each data item in Cortex XSOAR has a numeric incremental version. If Alice saved an item with version 4 and Bob trying to save the same item with version 3, Cortex XSOAR will rollback Bob request and returns a DB version conflict error. Bob will need to get the latest item and work on it so Alice work will not get lost.  Example request using 'curl'\\:  ``` curl 'https://hostname:443/incidents/search' -H 'content-type: application/json' -H 'accept: application/json' -H 'Authorization: <API Key goes here>' --data-binary '{\"filter\":{\"query\":\"-status:closed -category:job\",\"period\":{\"by\":\"day\",\"fromValue\":7}}}' --compressed ```  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RelationshipCommonFields(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entity_a': 'str',
        'entity_a_family': 'str',
        'entity_b': 'str',
        'entity_b_family': 'str',
        'name': 'str',
        'object_type_a': 'str',
        'object_type_b': 'str',
        'reverse_name': 'str'
    }

    attribute_map = {
        'entity_a': 'entityA',
        'entity_a_family': 'entityAFamily',
        'entity_b': 'entityB',
        'entity_b_family': 'entityBFamily',
        'name': 'name',
        'object_type_a': 'objectTypeA',
        'object_type_b': 'objectTypeB',
        'reverse_name': 'reverseName'
    }

    def __init__(self, entity_a=None, entity_a_family=None, entity_b=None, entity_b_family=None, name=None, object_type_a=None, object_type_b=None, reverse_name=None):  # noqa: E501
        """RelationshipCommonFields - a model defined in Swagger"""  # noqa: E501

        self._entity_a = None
        self._entity_a_family = None
        self._entity_b = None
        self._entity_b_family = None
        self._name = None
        self._object_type_a = None
        self._object_type_b = None
        self._reverse_name = None
        self.discriminator = None

        if entity_a is not None:
            self.entity_a = entity_a
        if entity_a_family is not None:
            self.entity_a_family = entity_a_family
        if entity_b is not None:
            self.entity_b = entity_b
        if entity_b_family is not None:
            self.entity_b_family = entity_b_family
        if name is not None:
            self.name = name
        if object_type_a is not None:
            self.object_type_a = object_type_a
        if object_type_b is not None:
            self.object_type_b = object_type_b
        if reverse_name is not None:
            self.reverse_name = reverse_name

    @property
    def entity_a(self):
        """Gets the entity_a of this RelationshipCommonFields.  # noqa: E501


        :return: The entity_a of this RelationshipCommonFields.  # noqa: E501
        :rtype: str
        """
        return self._entity_a

    @entity_a.setter
    def entity_a(self, entity_a):
        """Sets the entity_a of this RelationshipCommonFields.


        :param entity_a: The entity_a of this RelationshipCommonFields.  # noqa: E501
        :type: str
        """

        self._entity_a = entity_a

    @property
    def entity_a_family(self):
        """Gets the entity_a_family of this RelationshipCommonFields.  # noqa: E501


        :return: The entity_a_family of this RelationshipCommonFields.  # noqa: E501
        :rtype: str
        """
        return self._entity_a_family

    @entity_a_family.setter
    def entity_a_family(self, entity_a_family):
        """Sets the entity_a_family of this RelationshipCommonFields.


        :param entity_a_family: The entity_a_family of this RelationshipCommonFields.  # noqa: E501
        :type: str
        """

        self._entity_a_family = entity_a_family

    @property
    def entity_b(self):
        """Gets the entity_b of this RelationshipCommonFields.  # noqa: E501


        :return: The entity_b of this RelationshipCommonFields.  # noqa: E501
        :rtype: str
        """
        return self._entity_b

    @entity_b.setter
    def entity_b(self, entity_b):
        """Sets the entity_b of this RelationshipCommonFields.


        :param entity_b: The entity_b of this RelationshipCommonFields.  # noqa: E501
        :type: str
        """

        self._entity_b = entity_b

    @property
    def entity_b_family(self):
        """Gets the entity_b_family of this RelationshipCommonFields.  # noqa: E501


        :return: The entity_b_family of this RelationshipCommonFields.  # noqa: E501
        :rtype: str
        """
        return self._entity_b_family

    @entity_b_family.setter
    def entity_b_family(self, entity_b_family):
        """Sets the entity_b_family of this RelationshipCommonFields.


        :param entity_b_family: The entity_b_family of this RelationshipCommonFields.  # noqa: E501
        :type: str
        """

        self._entity_b_family = entity_b_family

    @property
    def name(self):
        """Gets the name of this RelationshipCommonFields.  # noqa: E501


        :return: The name of this RelationshipCommonFields.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RelationshipCommonFields.


        :param name: The name of this RelationshipCommonFields.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def object_type_a(self):
        """Gets the object_type_a of this RelationshipCommonFields.  # noqa: E501


        :return: The object_type_a of this RelationshipCommonFields.  # noqa: E501
        :rtype: str
        """
        return self._object_type_a

    @object_type_a.setter
    def object_type_a(self, object_type_a):
        """Sets the object_type_a of this RelationshipCommonFields.


        :param object_type_a: The object_type_a of this RelationshipCommonFields.  # noqa: E501
        :type: str
        """

        self._object_type_a = object_type_a

    @property
    def object_type_b(self):
        """Gets the object_type_b of this RelationshipCommonFields.  # noqa: E501


        :return: The object_type_b of this RelationshipCommonFields.  # noqa: E501
        :rtype: str
        """
        return self._object_type_b

    @object_type_b.setter
    def object_type_b(self, object_type_b):
        """Sets the object_type_b of this RelationshipCommonFields.


        :param object_type_b: The object_type_b of this RelationshipCommonFields.  # noqa: E501
        :type: str
        """

        self._object_type_b = object_type_b

    @property
    def reverse_name(self):
        """Gets the reverse_name of this RelationshipCommonFields.  # noqa: E501


        :return: The reverse_name of this RelationshipCommonFields.  # noqa: E501
        :rtype: str
        """
        return self._reverse_name

    @reverse_name.setter
    def reverse_name(self, reverse_name):
        """Sets the reverse_name of this RelationshipCommonFields.


        :param reverse_name: The reverse_name of this RelationshipCommonFields.  # noqa: E501
        :type: str
        """

        self._reverse_name = reverse_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RelationshipCommonFields, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RelationshipCommonFields):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
