# coding: utf-8

# flake8: noqa

"""
    Demisto API

    This is the public REST API to integrate with the demisto server. HTTP request can be sent using any HTTP-client.  For an example dedicated client take a look at: https://github.com/demisto/demisto-py.  Requests must include API-key that can be generated in the Demisto web client under 'Settings' -> 'Integrations' -> 'API keys'   Optimistic Locking and Versioning\\:  When using Demisto REST API, you will need to make sure to work on the latest version of the item (incident, entry, etc.), otherwise, you will get a DB version error (which not allow you to override a newer item). In addition, you can pass 'version\\: -1' to force data override (make sure that other users data might be lost).  Assume that Alice and Bob both read the same data from Demisto server, then they both changed the data, and then both tried to write the new versions back to the server. Whose changes should be saved? Alice’s? Bob’s? To solve this, each data item in Demisto has a numeric incremental version. If Alice saved an item with version 4 and Bob trying to save the same item with version 3, Demisto will rollback Bob request and returns a DB version conflict error. Bob will need to get the latest item and work on it so Alice work will not get lost.  Example request using 'curl'\\:  ``` curl 'https://hostname:443/incidents/search' -H 'content-type: application/json' -H 'accept: application/json' -H 'Authorization: <API Key goes here>' --data-binary '{\"filter\":{\"query\":\"-status:closed -category:job\",\"period\":{\"by\":\"day\",\"fromValue\":7}}}' --compressed ```  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from demisto.api.demisto_api import DemistoApi

# import ApiClient
from demisto.api_client import ApiClient
from demisto.configuration import Configuration
# import models into sdk package
from demisto.models.advance_arg import AdvanceArg
from demisto.models.arg_atomic_filter import ArgAtomicFilter
from demisto.models.arg_filter import ArgFilter
from demisto.models.arg_transformer import ArgTransformer
from demisto.models.argument import Argument
from demisto.models.array_positions import ArrayPositions
from demisto.models.attachment import Attachment
from demisto.models.audit import Audit
from demisto.models.audit_result import AuditResult
from demisto.models.automation_script import AutomationScript
from demisto.models.automation_script_api import AutomationScriptAPI
from demisto.models.automation_script_filter import AutomationScriptFilter
from demisto.models.automation_script_filter_wrapper import AutomationScriptFilterWrapper
from demisto.models.automation_script_result import AutomationScriptResult
from demisto.models.complex_arg import ComplexArg
from demisto.models.create_incident_request import CreateIncidentRequest
from demisto.models.custom_fields import CustomFields
from demisto.models.d_bot_score import DBotScore
from demisto.models.dashboard import Dashboard
from demisto.models.data_collection_form import DataCollectionForm
from demisto.models.date_range import DateRange
from demisto.models.date_range_filter import DateRangeFilter
from demisto.models.delete_evidence import DeleteEvidence
from demisto.models.docker_image import DockerImage
from demisto.models.docker_images_result import DockerImagesResult
from demisto.models.download_entry import DownloadEntry
from demisto.models.duration import Duration
from demisto.models.ending_type import EndingType
from demisto.models.entry import Entry
from demisto.models.entry_category import EntryCategory
from demisto.models.entry_history import EntryHistory
from demisto.models.entry_reputation import EntryReputation
from demisto.models.entry_task import EntryTask
from demisto.models.entry_type import EntryType
from demisto.models.evidence import Evidence
from demisto.models.evidence_data import EvidenceData
from demisto.models.evidences import Evidences
from demisto.models.evidences_filter_wrapper import EvidencesFilterWrapper
from demisto.models.evidences_search_response import EvidencesSearchResponse
from demisto.models.field_group import FieldGroup
from demisto.models.field_mapping import FieldMapping
from demisto.models.field_term_location_map import FieldTermLocationMap
from demisto.models.file_metadata import FileMetadata
from demisto.models.filter_cache import FilterCache
from demisto.models.filter_operator_id import FilterOperatorID
from demisto.models.generic_indicator_update_batch import GenericIndicatorUpdateBatch
from demisto.models.generic_string_date_filter import GenericStringDateFilter
from demisto.models.generic_string_filter import GenericStringFilter
from demisto.models.grid_column import GridColumn
from demisto.models.group import Group
from demisto.models.groups import Groups
from demisto.models.human_cron import HumanCron
from demisto.models.important import Important
from demisto.models.incident import Incident
from demisto.models.incident_field import IncidentField
from demisto.models.incident_filter import IncidentFilter
from demisto.models.incident_search_response_wrapper import IncidentSearchResponseWrapper
from demisto.models.incident_status import IncidentStatus
from demisto.models.incident_type import IncidentType
from demisto.models.incident_wrapper import IncidentWrapper
from demisto.models.indicator_context import IndicatorContext
from demisto.models.indicator_filter import IndicatorFilter
from demisto.models.indicator_result import IndicatorResult
from demisto.models.inline_response200 import InlineResponse200
from demisto.models.insight_cache import InsightCache
from demisto.models.inv_playbook_assignee import InvPlaybookAssignee
from demisto.models.inv_playbook_due import InvPlaybookDue
from demisto.models.inv_playbook_task_complete_data import InvPlaybookTaskCompleteData
from demisto.models.inv_playbook_task_data import InvPlaybookTaskData
from demisto.models.inv_task_info import InvTaskInfo
from demisto.models.investigation import Investigation
from demisto.models.investigation_filter import InvestigationFilter
from demisto.models.investigation_playbook import InvestigationPlaybook
from demisto.models.investigation_playbook_data import InvestigationPlaybookData
from demisto.models.investigation_playbook_state import InvestigationPlaybookState
from demisto.models.investigation_playbook_task import InvestigationPlaybookTask
from demisto.models.investigation_playbook_tasks_api import InvestigationPlaybookTasksAPI
from demisto.models.investigation_search_response import InvestigationSearchResponse
from demisto.models.investigation_status import InvestigationStatus
from demisto.models.investigation_type import InvestigationType
from demisto.models.investigations import Investigations
from demisto.models.ioc_object import IocObject
from demisto.models.ioc_objects import IocObjects
from demisto.models.label import Label
from demisto.models.location import Location
from demisto.models.locations import Locations
from demisto.models.module_args import ModuleArgs
from demisto.models.new_docker_image import NewDockerImage
from demisto.models.new_docker_image_result import NewDockerImageResult
from demisto.models.notifiable_item import NotifiableItem
from demisto.models.notify_timings import NotifyTimings
from demisto.models.operator_argument import OperatorArgument
from demisto.models.order import Order
from demisto.models.output import Output
from demisto.models.output_type import OutputType
from demisto.models.period import Period
from demisto.models.playbook_input import PlaybookInput
from demisto.models.playbook_inputs import PlaybookInputs
from demisto.models.playbook_output import PlaybookOutput
from demisto.models.playbook_outputs import PlaybookOutputs
from demisto.models.playbook_view import PlaybookView
from demisto.models.question import Question
from demisto.models.raw_message import RawMessage
from demisto.models.remote_repos import RemoteRepos
from demisto.models.report import Report
from demisto.models.report_automation import ReportAutomation
from demisto.models.report_fields_decoder import ReportFieldsDecoder
from demisto.models.report_query import ReportQuery
from demisto.models.reputation_calc_alg import ReputationCalcAlg
from demisto.models.reputation_data import ReputationData
from demisto.models.run_status import RunStatus
from demisto.models.sla import SLA
from demisto.models.sla_state import SLAState
from demisto.models.script_sub_type import ScriptSubType
from demisto.models.script_target import ScriptTarget
from demisto.models.script_type import ScriptType
from demisto.models.search_incidents_data import SearchIncidentsData
from demisto.models.section import Section
from demisto.models.section_item import SectionItem
from demisto.models.severity import Severity
from demisto.models.stats_query_response import StatsQueryResponse
from demisto.models.stats_text_response import StatsTextResponse
from demisto.models.stats_trends_response import StatsTrendsResponse
from demisto.models.system import System
from demisto.models.system_agent import SystemAgent
from demisto.models.task import Task
from demisto.models.task_condition import TaskCondition
from demisto.models.task_loop import TaskLoop
from demisto.models.task_state import TaskState
from demisto.models.task_type import TaskType
from demisto.models.task_view import TaskView
from demisto.models.term_location_map import TermLocationMap
from demisto.models.terminal_options import TerminalOptions
from demisto.models.timer_action import TimerAction
from demisto.models.timer_trigger import TimerTrigger
from demisto.models.transformer_operator_id import TransformerOperatorID
from demisto.models.update_data_batch import UpdateDataBatch
from demisto.models.update_entry import UpdateEntry
from demisto.models.update_entry_tags import UpdateEntryTags
from demisto.models.update_indicator_reputation_data import UpdateIndicatorReputationData
from demisto.models.update_response import UpdateResponse
from demisto.models.uploaded_entry import UploadedEntry
from demisto.models.widget import Widget
from demisto.models.widget_cell import WidgetCell
from demisto.models.widget_cells import WidgetCells
